import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--poppins",
  weight: '400',
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased flex flex-col h-screen justify-evenly w-80 m-auto p-2 text-center bg-[url(/bg-intro-mobile.png)]`}
      >
        {children}
      <footer className="text-center">Challenge by <a href="https://www.frontendmentor.io/home">Frontend Mentor</a>. Coded by <a href="https://github.com/chapucrespo">Chapu Crespo</a></footer>
      </body>
    </html>
  );
}